services:
  oak:
    image: "${registery_GPU}/ros2_rover:${ros2_rover_GPU_tag:?error}"
    container_name: oak
    hostname: oak
    restart: unless-stopped
    tty: true
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # network_mode: "host"
    networks:
      rover:
        ipv4_address: "10.20.10.2"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DISPLAY: ${DISPLAY}
      - XAUTHORITY: ${XAUTH}
        
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /dev:/dev/
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./launchFiles:/home/rover/ws_rover/volume/launchFiles

    # command: /bin/bash -c "sleep inf"
      
    # command: /bin/bash -c "
    #   ros2 launch depthai_examples stereo_inertial_node.launch.py "
    #   depth_aligned:=True \
    #   monoResolution:=400p \
    #   rgbResolution:=720p \
    #   enableSpatialDetection:=False \
    #   enableRviz:=True \
    #   syncNN:=False \
    #   mode:=rectified \
    #   enable_imu:=true"

    command: /bin/bash -c "
      ros2 launch /home/rover/ws_rover/volume/launchFiles/oak-rgbd.launch.py "

  StaticTransform:
    image: "${registery_GPU}/ros2_rover:${ros2_rover_GPU_tag:?error}"
    container_name: st
    hostname: st
    tty: true
    privileged: true
    depends_on:
      - oak
    restart: unless-stopped
    # network_mode: "host"
    networks:
      rover:
        ipv4_address: "10.20.10.3"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    #   DISPLAY: ${DISPLAY}
    #   XAUTHORITY: ${XAUTH}
        
    volumes:
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw

    # command: /bin/bash -c "sleep inf"
    # entrypoint: ["/bin/sh", "-c"]

    command: /bin/bash -c "
      ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 base_link oak-d-base-frame "

  imu_filter:
    image: "${registery_GPU}/ros2_rover:${ros2_rover_GPU_tag:?error}"
    container_name: imu_filter
    privileged: true
    # restart: unless-stopped
    # network_mode: "host"
    networks:
      rover:
        ipv4_address: "10.20.10.4"
    depends_on:
      # - roscore
      - oak
    # environment:
    #   DISPLAY: ${DISPLAY}
    #   "XAUTHORITY": ${XAUTH}
    volumes:
      - ./launchFiles:/home/rover/ws_rover/volume/launchFiles
    command: /bin/bash -c ". /home/rover/ws_rover/volume/launchFiles/start_imu_filter.bash"

  Rtabmap:
    image: "${registery_GPU}/ros2_rover:${ros2_rover_GPU_tag:?error}"
    container_name: rtabmap
    hostname: rtabmap
    tty: true
    privileged: true
    restart: unless-stopped
    depends_on:
      - StaticTransform
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # network_mode: "host"
    networks:
      rover:
        ipv4_address: "10.20.10.5"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DISPLAY: ${DISPLAY}
      - XAUTHORITY: ${XAUTH}
        
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./launchFiles:/home/rover/ws_rover/volume/launchFiles

    # command: /bin/bash -c "sleep inf"
    # entrypoint: ["/bin/sh", "-c"]

    command: /bin/bash -c "
      . /home/rover/ws_rover/volume/launchFiles/start_rtabmap_rgbd.bash "

  Nav2:
    image: "${registery_GPU}/ros2_rover:${ros2_rover_GPU_tag:?error}"
    container_name: nav2
    hostname: nav2
    tty: true
    privileged: true
    restart: unless-stopped
    depends_on:
      - Rtabmap
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # network_mode: "host"
    networks:
      rover:
        ipv4_address: "10.20.10.6"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DISPLAY: ${DISPLAY}
      - XAUTHORITY: ${XAUTH}
        
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./launchFiles:/home/rover/ws_rover/volume/launchFiles

  #   # command: /bin/bash -c "sleep inf"
  #   # entrypoint: ["/bin/sh", "-c"]

    command: /bin/bash -c "
      ros2 launch nav2_bringup navigation_launch.py params_file:=/home/rover/ws_rover/volume/launchFiles/nav2_icp.yaml  "

  Nav2_rviz:
    image: "${registery_GPU}/ros2_rover:${ros2_rover_GPU_tag:?error}"
    container_name: nav2_rviz
    hostname: nav2_rivz
    tty: true
    privileged: true
    restart: unless-stopped
    depends_on:
      - Nav2
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # network_mode: "host"
    networks:
      rover:
        ipv4_address: "10.20.10.7"

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTH}

        
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./:/home/rover/ws_rover/volume/

    # command: /bin/bash -c "sleep inf"
    # entrypoint: ["/bin/sh", "-c"]

    command: /bin/bash -c "
      ros2 launch nav2_bringup rviz_launch.py "
    




  # rviz2:
  #   image: "${registery_GPU}/ros2_rover:${ros2_rover_GPU_tag:?error}"
  #   container_name: rviz2
  #   hostname: rviz2
  #   tty: true
  #   # network_mode: "host"
  #   networks:
  #     rover:
  #       ipv4_address: "10.20.10.10"
  #   # restart: unless-stopped
  #   depends_on:
  #     - Lidar
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    #   - DISPLAY=${DISPLAY}
    #   - XAUTHORITY=${XAUTH}

  #   volumes:
  #     - /tmp/.X11-unix/:/tmp/.X11-unix/
  #   command: /bin/bash -c "
  #     source /home/rover/ws_rover/install/setup.bash && rviz2 -d "



networks:
  rover:
    ipam:
      driver: default
      config:
        - subnet: "10.20.10.0/24"
