/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: false
      i_nn_type: none
      # i_laser_dot_brightness: 1200
      i_pipeline_type: RGBD    # to get rectify image should be in depth mode  RGBstereo
      # i_pipeline_type:
      #   Depth
        # if setting to depth mode the external calibration will be ignored
        # in stereo mode the external calibration will just apply to camera_info topic

      i_publish_synced_rect_pair: true

    imu:
      i_acc_freq: 100  # Accelerometer sensor frequency
      i_gyro_freq: 100 # Gyroscope frequency
      i_rot_freq: 100  # Rotation frequency
      
    stereo:
      i_publish_right_rect: false
      i_publish_left_rect: false
      i_publish_synced_rect_pair: true
      i_reverse_stereo_socket_order: true
      i_stereo_conf_threshold: 90
      i_subpixel: false
      i_publish_topic: false

    rgb:
      # i_low_bandwidth: true
      i_resolution: "1080P"
      i_fps: 30.0

    left:
      i_rect: true
      i_resolution: "720p"
      i_fps: 30.0
      i_low_bandwidth: true
      i_publish_topic: false

    right:
      i_rect: false
      i_resolution: "720p"
      i_fps: 30.0
      i_low_bandwidth: true
      i_publish_topic: false

