ARG ROS_DISTRO=jazzy
FROM ros:${ROS_DISTRO}-ros-base

LABEL maintainer="Parsa Khaledi <pa.aerospace@gmail.com>"

SHELL ["/bin/bash", "-c"]

ARG USER_NAME=rover
ARG USER_UID=1000
ARG USER_GID=1000

ENV DEBIAN_FRONTEND=noninteractive
ENV QT_X11_NO_MITSHM=1
ENV LANG=en_US.UTF-8
ENV ROS2_INSTALL_PATH=/opt/ros/$ROS_DISTRO
ENV WORKDIR=/home/${USER_NAME}/ws_rover
ENV ROS_DISTRO=jazzy
WORKDIR ${WORKDIR}

### Install essentials, Nav2 and rtabmap 
RUN apt update	&& apt upgrade -y  && \
	apt install -y --no-install-recommends \
	vim udev git sudo unzip curl cmake wget tmux apt-utils\
	ros-dev-tools \
	xauth xorg openbox python3-argcomplete python3 python3-pip \
	ros-$ROS_DISTRO-rclcpp \
	ros-$ROS_DISTRO-rmw-cyclonedds-cpp \
	ros-$ROS_DISTRO-rviz2* \
	ros-$ROS_DISTRO-rqt ros-$ROS_DISTRO-rqt-image-view \
	ros-$ROS_DISTRO-rqt-graph ros-$ROS_DISTRO-rqt-topic \
	ros-$ROS_DISTRO-rqt-tf-tree \
	ros-$ROS_DISTRO-depthai-ros \
	ros-$ROS_DISTRO-imu-filter-madgwick \
	ros-$ROS_DISTRO-navigation2 ros-$ROS_DISTRO-nav2-bringup \
	ros-$ROS_DISTRO-rtabmap-ros 

### Set User	
RUN set -eux; \
    if getent group ${USER_NAME}; then \
      echo "Group $USER_NAME exists, not creating."; \
    else \
      groupadd ${USER_NAME} --gid ${USER_GID}; \
    fi; \
    useradd -l -m ${USER_NAME} -u ${USER_UID} -g ${USER_GID} -s /bin/bash && \
	echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER_NAME} && \
	chmod 0440 /etc/sudoers.d/${USER_NAME} && chown -R ${USER_NAME}:${USER_NAME} /home/${USER_NAME}/ 

### Change user
USER ${USER_NAME}

### Install sllidar_ros2
RUN mkdir ${WORKDIR}/src && cd ${WORKDIR}/ && git clone https://github.com/Slamtec/sllidar_ros2.git ./src && \
	source /opt/ros/$ROS_DISTRO/setup.bash && colcon build --symlink-install

### Install Micro XRCE-DDS
# RUN cd /${USER_NAME} && git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git && \
# 	cd /${USER_NAME}/Micro-XRCE-DDS-Agent &&\
# 	mkdir build && cd build && cmake .. &&\
# 	make && sudo make install && sudo ldconfig /usr/local/lib/ &&\
# 	cd /${USER_NAME} && rm -rf /Micro-XRCE-DDS-Agent/build

### Build WS (px4_ros_com && px4_msgs)
# RUN mkdir -p ${WORKDIR}/src
# RUN cd ${WORKDIR}/src && git clone -b release/1.15 https://github.com/PX4/px4_msgs.git
# RUN cd ${WORKDIR}/src && git clone https://github.com/PX4/px4_ros_com.git
# RUN source /opt/ros/$ROS_DISTRO/setup.bash && cd ${WORKDIR} && colcon build

### Tumux conf
RUN echo "set -g mouse on" >> ~/.tmux.conf 

### Write in ~/.bashrc
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc && \
	echo "source ${WORKDIR}/install/setup.bash" >> ~/.bashrc 
	# export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # For using cyclonedds

### Finilize
USER root
RUN rm -rf /var/lib/apt/lists/* &&\
	apt autoremove -y 
USER ${USER_NAME}
