name: Docker Image Rover No GPU CI

on:
  push:
    paths:
      - 'dockerFile/Dockerfile_rover'
      - '.github/workflows/docker-image_rover_NO_GPU.yml'
    # branches: [ "docker" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  Registery: docker.io
  ImageName: alienkh/ros2_rover
  ImageTag: ${{ github.run_number }}

jobs:

  build_and_push_docker_image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
            
    steps:
      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          platforms: ${{ matrix.platform }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.Registery }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.Registery }}/${{ env.ImageName }}
          tags: ${{ env.ImageTag }}
      
      - name: Build and Push docker image for not using GPU
        id: build-and-push-rover
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.Registery }}/${{ env.ImageName }}:${{ env.ImageTag }}
          platforms: ${{ matrix.platform }}
          file: ./dockerFile/Dockerfile_rover
          build-args: |
            BUILD_DATE=${DATE_RFC3339}
            VERSION=${VERSION}
            COMMIT_SHA=${GITHUB_SHA}
